In [24]:
import pandas as pd
pd.set_option('display.max_columns', 500)

In [5]:
summary_data = pd.read_csv('massey_seasons_with_id.csv')
summary_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5454 entries, 0 to 5453
Data columns (total 13 columns):
SAG          5454 non-null int64
WLK          5454 non-null float64
WOL          5454 non-null int64
Team         5454 non-null object
RTH          5454 non-null int64
COL          5454 non-null float64
POM          5454 non-null float64
DOL          5454 non-null float64
RPI          5454 non-null float64
MOR          5454 non-null object
season       5454 non-null int64
win_pct      5454 non-null float64
kaggle_id    5454 non-null object
dtypes: float64(6), int64(4), object(3)
memory usage: 554.0+ KB

In [6]:
summary_data.describe()

,SAG,WLK,WOL,RTH,COL,POM,DOL,RPI,season,win_pct
count,5454.000000,5454.000000,5454.000000,5454.000000,5454.000000,5454.000000,5454.000000,5454.000000,5454.000000,5454.000000
mean,171.387055,171.340484,171.412725,171.364503,171.321782,171.310231,171.341217,171.283645,2010.621746,0.513328
std,98.977414,98.926046,98.995735,98.973345,98.887448,98.906044,98.922645,98.868126,4.595077,0.179117
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2003.000000,0.000000
25%,86.000000,86.000000,86.000000,86.000000,86.000000,86.000000,86.000000,86.000000,2007.000000,0.387097
50%,171.000000,171.000000,171.000000,171.000000,171.000000,171.000000,171.000000,171.000000,2011.000000,0.515152
75%,257.000000,257.000000,257.000000,257.000000,256.750000,257.000000,257.000000,256.000000,2015.000000,0.645161
max,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000,2018.000000,1.000000

In [8]:
summary_data = summary_data[summary_data['season'] < 2018]
summary_data.describe()['season']

count    5103.000000
mean     2010.114247
std         4.308661
min      2003.000000
25%      2006.000000
50%      2010.000000
75%      2014.000000
max      2017.000000
Name: season, dtype: float64

In [13]:
tourney_data = pd.read_csv('tournament_results.csv')
tourney_data.drop(columns=['days_from_epoch','day','num_ot','academic_year','win_region','win_alias','lose_region',
                           'lose_alias','lose_code_ncaa','win_school_ncaa','win_code_ncaa','win_name','lose_name',
                           'win_pts','win_kaggle_team_id','lose_school_ncaa','lose_kaggle_team_id','lose_pts'],inplace=True)
tourney_data['train_rec'] = 0
tourney_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2117 entries, 0 to 2116
Data columns (total 10 columns):
season          2117 non-null int64
round           2117 non-null int64
game_date       2117 non-null object
win_seed        2117 non-null int64
win_market      2117 non-null object
win_team_id     2117 non-null object
lose_seed       2117 non-null int64
lose_market     2117 non-null object
lose_team_id    2117 non-null object
train_rec       2117 non-null int64
dtypes: int64(5), object(5)
memory usage: 165.5+ KB

In [14]:
tourney_data = tourney_data[tourney_data['season'] >= 2003]
tourney_data.describe()['season']

count     981.000000
mean     2010.085627
std         4.325153
min      2003.000000
25%      2006.000000
50%      2010.000000
75%      2014.000000
max      2017.000000
Name: season, dtype: float64

In [15]:
tourney_data['game_result'] = 1
tourney_data.game_result = tourney_data.game_result.astype(int)
tourney_data.rename(columns={"win_seed":"team_seed","win_market":"team","win_team_id":"team_id"}, inplace=True)
tourney_data.rename(columns={"lose_seed":"opp_team_seed","lose_market":"opp_team","lose_team_id":"opp_team_id"}, inplace=True)
tourney_data['start_season'] = tourney_data['season'] -1
tourney_data

,season,round,game_date,team_seed,team,team_id,opp_team_seed,opp_team,opp_team_id,train_rec,game_result,start_season
10,2013,64,2013-03-22,9,Temple,8598d1b6-106b-4083-a512-2e495729525a,8,North Carolina State,52df1e19-b142-4a76-a439-ad68455d0581,0,1,2012
17,2011,64,2011-03-17,7,Temple,8598d1b6-106b-4083-a512-2e495729525a,10,Penn State,4aebd148-8119-4875-954c-66779867989b,0,1,2010
27,2013,64,2013-03-21,5,Virginia Commonwealth,c1c1e6df-a383-4fbd-ba7b-32d4f9ef9518,12,Akron,56fe0ab2-e4f0-47b9-8726-9ce23ebcde20,0,1,2012
29,2012,64,2012-03-15,12,Virginia Commonwealth,c1c1e6df-a383-4fbd-ba7b-32d4f9ef9518,5,Wichita State,f38b58de-3273-4723-a78b-2f918e9aa2d5,0,1,2011
30,2011,8,2011-03-27,11,Virginia Commonwealth,c1c1e6df-a383-4fbd-ba7b-32d4f9ef9518,1,Kansas,fae4855b-1b64-4b40-a632-9ed345e1e952,0,1,2010
31,2011,16,2011-03-25,11,Virginia Commonwealth,c1c1e6df-a383-4fbd-ba7b-32d4f9ef9518,10,Florida State,d3c8a767-b6fc-45d4-a5f2-18406f2993f1,0,1,2010
32,2007,64,2007-03-15,11,Virginia Commonwealth,c1c1e6df-a383-4fbd-ba7b-32d4f9ef9518,6,Duke,faeb1160-5d15-4f26-99fc-c441cf21fc7f,0,1,2006
33,2011,32,2011-03-20,11,Virginia Commonwealth,c1c1e6df-a383-4fbd-ba7b-32d4f9ef9518,3,Purdue,12d7f888-675b-459f-9099-a38f771d8a95,0,1,2010
34,2011,64,2011-03-18,11,Virginia Commonwealth,c1c1e6df-a383-4fbd-ba7b-32d4f9ef9518,6,Georgetown,8736b67f-5924-400b-bf94-3bd804c36600,0,1,2010
35,2011,68,2011-03-16,11,Virginia Commonwealth,c1c1e6df-a383-4fbd-ba7b-32d4f9ef9518,11,USC,3a000455-de7c-4ca8-880e-abdce7f21da9,0,1,2010
36,2016,64,2016-03-18,10,Virginia Commonwealth,c1c1e6df-a383-4fbd-ba7b-32d4f9ef9518,7,Oregon State,532d3874-b4b3-4c5c-acc6-749a6db26c8f,0,1,2015
37,2013,64,2013-03-21,8,Colorado State,1a470730-f328-4fb1-8bbf-36a069e4d6b2,9,Missouri,77ca152a-cb2f-48a5-97b2-492351250d94,0,1,2012
44,2017,64,2017-03-17,11,Rhode Island,7e42bca2-3cd7-4aca-aa46-f190fe5d8eb4,6,Creighton,7d797407-623e-476d-b299-46de4275414d,0,1,2016
46,2015,64,2015-03-19,5,Utah,0d037a5d-827a-44dd-8b70-57603d671d5d,12,Stephen F. Austin,5ef64f01-86ae-4553-9834-c79cc0859eaf,0,1,2014
48,2016,64,2016-03-17,3,Utah,0d037a5d-827a-44dd-8b70-57603d671d5d,14,Fresno State,dd8db4d8-d984-4cab-b7f6-22c6b8c2c45f,0,1,2015
49,2015,32,2015-03-21,5,Utah,0d037a5d-827a-44dd-8b70-57603d671d5d,4,Georgetown,8736b67f-5924-400b-bf94-3bd804c36600,0,1,2014
60,2005,64,2005-03-17,6,Utah,0d037a5d-827a-44dd-8b70-57603d671d5d,11,UTEP,06d15d35-4955-4fdd-83d9-32d24dbd795b,0,1,2004
61,2003,64,2003-03-21,9,Utah,0d037a5d-827a-44dd-8b70-57603d671d5d,8,Oregon,1da70895-f77f-44ef-b216-d63c02e696eb,0,1,2002
62,2005,32,2005-03-19,6,Utah,0d037a5d-827a-44dd-8b70-57603d671d5d,3,Oklahoma,b2fda957-e15c-4fb2-8a13-6e58496f561e,0,1,2004
72,2017,64,2017-03-17,3,Baylor,db6e1cab-3fa3-4a93-a673-8b2a358ff4bf,14,New Mexico State,5016fe1a-9571-4d10-bf5b-b9c1b496bd57,0,1,2016
73,2017,32,2017-03-19,3,Baylor,db6e1cab-3fa3-4a93-a673-8b2a358ff4bf,11,USC,3a000455-de7c-4ca8-880e-abdce7f21da9,0,1,2016
74,2010,32,2010-03-20,3,Baylor,db6e1cab-3fa3-4a93-a673-8b2a358ff4bf,11,Old Dominion,ce967953-5c50-4220-87b2-99acb9606e84,0,1,2009
75,2010,64,2010-03-18,3,Baylor,db6e1cab-3fa3-4a93-a673-8b2a358ff4bf,14,Sam Houston State,67322042-9c40-4dc2-b33a-4754c02ec82a,0,1,2009
76,2010,16,2010-03-26,3,Baylor,db6e1cab-3fa3-4a93-a673-8b2a358ff4bf,10,Saint Mary's,b18f34af-a7f1-4659-a2e5-fc11a31cd316,0,1,2009
77,2012,16,2012-03-23,3,Baylor,db6e1cab-3fa3-4a93-a673-8b2a358ff4bf,10,Xavier,0d8a328f-20ce-410b-bed1-15fc01308aaf,0,1,2011
78,2012,64,2012-03-15,3,Baylor,db6e1cab-3fa3-4a93-a673-8b2a358ff4bf,14,South Dakota State,6ef40534-5fad-4755-84de-7dcbd645d1f0,0,1,2011
79,2012,32,2012-03-17,3,Baylor,db6e1cab-3fa3-4a93-a673-8b2a358ff4bf,11,Colorado,9fccbf28-2858-4263-821c-fdefb3c7efa3,0,1,2011
80,2014,64,2014-03-21,6,Baylor,db6e1cab-3fa3-4a93-a673-8b2a358ff4bf,11,Nebraska,f8b1bf00-5b73-4ac4-98c0-ec554027ae32,0,1,2013
81,2014,32,2014-03-23,6,Baylor,db6e1cab-3fa3-4a93-a673-8b2a358ff4bf,3,Creighton,7d797407-623e-476d-b299-46de4275414d,0,1,2013
82,2014,64,2014-03-21,14,Mercer,a14b0057-8eb5-43d2-a33b-666196da933e,3,Duke,faeb1160-5d15-4f26-99fc-c441cf21fc7f,0,1,2013
...,...,...,...,...,...,...,...,...,...,...,...,...
2028,2016,64,2016-03-18,6,Notre Dame,80962f09-8821-48b6-8cf0-0cf0eea56aa8,11,Michigan,bdc2561d-f603-4fab-a262-f1d2af462277,0,1,2015
2029,2017,64,2017-03-16,5,Notre Dame,80962f09-8821-48b6-8cf0-0cf0eea56aa8,12,Princeton,fe406882-9f22-495e-9df6-ef357a6803c6,0,1,2016
2030,2015,32,2015-03-21,3,Notre Dame,80962f09-8821-48b6-8cf0-0cf0eea56aa8,6,Butler,bdb7d7a4-45f8-4bf3-ab85-15488c451494,0,1,2014
2031,2015,16,2015-03-26,3,Notre Dame,80962f09-8821-48b6-8cf0-0cf0eea56aa8,7,Wichita State,f38b58de-3273-4723-a78b-2f918e9aa2d5,0,1,2014
2034,2015,64,2015-03-19,3,Notre Dame,80962f09-8821-48b6-8cf0-0cf0eea56aa8,14,Northeastern,93df9b18-e9fc-42a7-bb45-a736c203b4dc,0,1,2014
2036,2003,64,2003-03-20,5,Notre Dame,80962f09-8821-48b6-8cf0-0cf0eea56aa8,12,Milwaukee,5d77800f-1ae6-4b66-8e97-b0dbb8bbc717,0,1,2002
2037,2011,64,2011-03-18,2,Notre Dame,80962f09-8821-48b6-8cf0-0cf0eea56aa8,15,Akron,56fe0ab2-e4f0-47b9-8726-9ce23ebcde20,0,1,2010
2038,2003,32,2003-03-22,5,Notre Dame,80962f09-8821-48b6-8cf0-0cf0eea56aa8,4,Illinois,150148c2-ca8f-414f-8f41-d94a55d4a122,0,1,2002
2045,2013,64,2013-03-22,11,Minnesota,fa416692-7e09-4f0a-9bcf-0cf7d5149a14,6,UCLA,ec0d6b67-4b16-4b50-92b2-1a651dae6b0f,0,1,2012
2054,2012,64,2012-03-16,15,Lehigh,508f503f-dc57-4f4c-a01e-4f195e5c05c8,2,Duke,faeb1160-5d15-4f26-99fc-c441cf21fc7f,0,1,2011
2057,2005,64,2005-03-18,5,Georgia Tech,0f63a6f5-bda7-4fd9-9271-8d33f555ca19,12,George Washington,d52c3640-069c-4554-982e-e6537c8044f1,0,1,2004
2064,2010,64,2010-03-19,10,Georgia Tech,0f63a6f5-bda7-4fd9-9271-8d33f555ca19,7,Oklahoma State,8ab00d43-840a-4c96-bdee-bf88fa6e3f11,0,1,2009
2072,2004,4,2004-04-03,3,Georgia Tech,0f63a6f5-bda7-4fd9-9271-8d33f555ca19,2,Oklahoma State,8ab00d43-840a-4c96-bdee-bf88fa6e3f11,0,1,2003
2073,2004,32,2004-03-21,3,Georgia Tech,0f63a6f5-bda7-4fd9-9271-8d33f555ca19,6,Boston College,4b3ff02c-e0ba-435b-a565-6075bc491684,0,1,2003
2074,2004,8,2004-03-28,3,Georgia Tech,0f63a6f5-bda7-4fd9-9271-8d33f555ca19,4,Kansas,fae4855b-1b64-4b40-a632-9ed345e1e952,0,1,2003
2075,2004,16,2004-03-26,3,Georgia Tech,0f63a6f5-bda7-4fd9-9271-8d33f555ca19,10,Nevada,62a73b4a-e281-4483-a1f8-f1160a18e456,0,1,2003
2076,2004,64,2004-03-19,3,Georgia Tech,0f63a6f5-bda7-4fd9-9271-8d33f555ca19,14,Northern Iowa,2c93a75d-5449-4ec1-9ca2-1e6c812399a4,0,1,2003
2079,2004,64,2004-03-19,5,Illinois,150148c2-ca8f-414f-8f41-d94a55d4a122,12,Murray State,77a69fb0-1355-4342-ac09-b4cc7949d95e,0,1,2003
2081,2004,32,2004-03-21,5,Illinois,150148c2-ca8f-414f-8f41-d94a55d4a122,4,Cincinnati,a17dfc54-415f-49c3-a2e6-d6fa9db18b0a,0,1,2003
2082,2013,64,2013-03-22,7,Illinois,150148c2-ca8f-414f-8f41-d94a55d4a122,10,Colorado,9fccbf28-2858-4263-821c-fdefb3c7efa3,0,1,2012
2084,2005,16,2005-03-24,1,Illinois,150148c2-ca8f-414f-8f41-d94a55d4a122,12,Milwaukee,5d77800f-1ae6-4b66-8e97-b0dbb8bbc717,0,1,2004
2085,2005,64,2005-03-17,1,Illinois,150148c2-ca8f-414f-8f41-d94a55d4a122,16,Fairleigh Dickinson,b71d5a1b-2671-4e5a-b94b-06bfb22a27dd,0,1,2004
2087,2005,32,2005-03-19,1,Illinois,150148c2-ca8f-414f-8f41-d94a55d4a122,9,Nevada,62a73b4a-e281-4483-a1f8-f1160a18e456,0,1,2004
2088,2005,4,2005-04-02,1,Illinois,150148c2-ca8f-414f-8f41-d94a55d4a122,4,Louisville,b795ddbc-baab-4499-8803-52e8608520ab,0,1,2004
2089,2005,8,2005-03-26,1,Illinois,150148c2-ca8f-414f-8f41-d94a55d4a122,3,Arizona,9b166a3f-e64b-4825-bb6b-92c6f0418263,0,1,2004
2102,2003,64,2003-03-20,4,Illinois,150148c2-ca8f-414f-8f41-d94a55d4a122,13,Western Kentucky,881380da-861c-4ab6-a7d2-20699d8ea883,0,1,2002
2103,2006,64,2006-03-16,4,Illinois,150148c2-ca8f-414f-8f41-d94a55d4a122,13,Air Force,aa7af640-5762-4686-9181-39f7b8a8186e,0,1,2005
2104,2011,64,2011-03-18,9,Illinois,150148c2-ca8f-414f-8f41-d94a55d4a122,8,UNLV,68a3227f-677f-43b0-9a3a-cad79d0df9e2,0,1,2010
2105,2005,68,2005-03-15,16,Oakland,aeaaef0d-5238-414e-ac04-c55a22cba208,16,Alabama A&M,949c3398-85e4-4c63-ba71-9a82e06ddea4,0,1,2004
2115,2003,64,2003-03-20,13,Tulsa,2959bd24-7007-41ae-a3a3-abdf26888cfc,4,Dayton,632616c5-2dbb-4017-a449-c9dfc303f026,0,1,2002

In [19]:
tourney_data['copy_team'] = tourney_data['team']
tourney_data['copy_team_seed'] = tourney_data['team_seed']
tourney_data['copy_team_id'] = tourney_data['team_id']

#swap the team and opp team data
tourney_data.loc[1::2,'team'] = tourney_data.loc[1::2,'opp_team']
tourney_data.loc[1::2,'opp_team'] = tourney_data.loc[1::2,'copy_team']
tourney_data.loc[1::2,'team_seed'] = tourney_data.loc[1::2,'opp_team_seed']
tourney_data.loc[1::2,'opp_team_seed'] = tourney_data.loc[1::2,'copy_team_seed']
tourney_data.loc[1::2,'team_id'] = tourney_data.loc[1::2,'opp_team_id']
tourney_data.loc[1::2,'opp_team_id'] = tourney_data.loc[1::2,'copy_team_id']

# flip the game result
tourney_data.loc[1::2,'game_result'] = 0

#drop the temporary columns
tourney_data.drop(columns=['copy_team','copy_team_seed','copy_team_id'],inplace=True)
tourney_data.head()

,season,round,game_date,team_seed,team,team_id,opp_team_seed,opp_team,opp_team_id,train_rec,game_result,start_season
10,2013,64,2013-03-22,9,Temple,8598d1b6-106b-4083-a512-2e495729525a,8,North Carolina State,52df1e19-b142-4a76-a439-ad68455d0581,0,0,2012
17,2011,64,2011-03-17,7,Temple,8598d1b6-106b-4083-a512-2e495729525a,10,Penn State,4aebd148-8119-4875-954c-66779867989b,0,1,2010
27,2013,64,2013-03-21,5,Virginia Commonwealth,c1c1e6df-a383-4fbd-ba7b-32d4f9ef9518,12,Akron,56fe0ab2-e4f0-47b9-8726-9ce23ebcde20,0,0,2012
29,2012,64,2012-03-15,12,Virginia Commonwealth,c1c1e6df-a383-4fbd-ba7b-32d4f9ef9518,5,Wichita State,f38b58de-3273-4723-a78b-2f918e9aa2d5,0,1,2011
30,2011,8,2011-03-27,11,Virginia Commonwealth,c1c1e6df-a383-4fbd-ba7b-32d4f9ef9518,1,Kansas,fae4855b-1b64-4b40-a632-9ed345e1e952,0,0,2010

In [20]:

m_tourney_data = tourney_data.merge(summary_data, left_on=['start_season','team_id'], 
                                right_on=['season', 'kaggle_id'],how='left',suffixes=('','_y'))

m_tourney_data.drop(columns=['season_y','kaggle_id'],inplace=True)

In [21]:
m_tourney_data.head()

,season,round,game_date,team_seed,team,team_id,opp_team_seed,opp_team,opp_team_id,train_rec,...,WLK,WOL,Team,RTH,COL,POM,DOL,RPI,MOR,win_pct
0,2013,64,2013-03-22,9,Temple,8598d1b6-106b-4083-a512-2e495729525a,8,North Carolina State,52df1e19-b142-4a76-a439-ad68455d0581,0,...,29.0,28.0,Temple,35.0,22.0,34.0,20.0,20.0,42,0.774194
1,2011,64,2011-03-17,7,Temple,8598d1b6-106b-4083-a512-2e495729525a,10,Penn State,4aebd148-8119-4875-954c-66779867989b,0,...,8.0,6.0,Temple,12.0,7.0,18.0,13.0,8.0,35,0.852941
2,2013,64,2013-03-21,5,Virginia Commonwealth,c1c1e6df-a383-4fbd-ba7b-32d4f9ef9518,12,Akron,56fe0ab2-e4f0-47b9-8726-9ce23ebcde20,0,...,43.0,32.0,VA Commonwealth,54.0,35.0,47.0,33.0,38.0,55,0.823529
3,2012,64,2012-03-15,12,Virginia Commonwealth,c1c1e6df-a383-4fbd-ba7b-32d4f9ef9518,5,Wichita State,f38b58de-3273-4723-a78b-2f918e9aa2d5,0,...,55.0,54.0,VA Commonwealth,74.0,59.0,84.0,72.0,49.0,80,0.676471
4,2011,8,2011-03-27,11,Virginia Commonwealth,c1c1e6df-a383-4fbd-ba7b-32d4f9ef9518,1,Kansas,fae4855b-1b64-4b40-a632-9ed345e1e952,0,...,61.0,72.0,VA Commonwealth,74.0,64.0,53.0,73.0,66.0,56,0.709677

In [22]:
tourney_data = m_tourney_data.merge(summary_data, left_on=['start_season','opp_team_id'], 
                                right_on=['season', 'kaggle_id'], how='left',suffixes=('_t','_o'))

In [25]:
tourney_data.head()

,season_t,round,game_date,team_seed,team,team_id,opp_team_seed,opp_team,opp_team_id,train_rec,game_result,start_season,SAG_t,WLK_t,WOL_t,Team_t,RTH_t,COL_t,POM_t,DOL_t,RPI_t,MOR_t,win_pct_t,SAG_o,WLK_o,WOL_o,Team_o,RTH_o,COL_o,POM_o,DOL_o,RPI_o,MOR_o,season_o,win_pct_o,kaggle_id
0,2013,64,2013-03-22,9,Temple,8598d1b6-106b-4083-a512-2e495729525a,8,North Carolina State,52df1e19-b142-4a76-a439-ad68455d0581,0,0,2012,36.0,29.0,28.0,Temple,35.0,22.0,34.0,20.0,20.0,42,0.774194,45.0,41.0,52.0,NC State,41.0,42.0,43.0,48.0,49.0,31,2012.0,0.647059,52df1e19-b142-4a76-a439-ad68455d0581
1,2011,64,2011-03-17,7,Temple,8598d1b6-106b-4083-a512-2e495729525a,10,Penn State,4aebd148-8119-4875-954c-66779867989b,0,1,2010,16.0,8.0,6.0,Temple,12.0,7.0,18.0,13.0,8.0,35,0.852941,130.0,159.0,197.0,Penn St,124.0,195.0,92.0,153.0,194.0,63,2010.0,0.354839,4aebd148-8119-4875-954c-66779867989b
2,2013,64,2013-03-21,5,Virginia Commonwealth,c1c1e6df-a383-4fbd-ba7b-32d4f9ef9518,12,Akron,56fe0ab2-e4f0-47b9-8726-9ce23ebcde20,0,0,2012,50.0,43.0,32.0,VA Commonwealth,54.0,35.0,47.0,33.0,38.0,55,0.823529,74.0,75.0,65.0,Akron,88.0,82.0,78.0,77.0,55.0,88,2012.0,0.666667,56fe0ab2-e4f0-47b9-8726-9ce23ebcde20
3,2012,64,2012-03-15,12,Virginia Commonwealth,c1c1e6df-a383-4fbd-ba7b-32d4f9ef9518,5,Wichita State,f38b58de-3273-4723-a78b-2f918e9aa2d5,0,1,2011,77.0,55.0,54.0,VA Commonwealth,74.0,59.0,84.0,72.0,49.0,80,0.676471,64.0,61.0,64.0,Wichita St,61.0,57.0,63.0,73.0,60.0,62,2011.0,0.750000,f38b58de-3273-4723-a78b-2f918e9aa2d5
4,2011,8,2011-03-27,11,Virginia Commonwealth,c1c1e6df-a383-4fbd-ba7b-32d4f9ef9518,1,Kansas,fae4855b-1b64-4b40-a632-9ed345e1e952,0,0,2010,67.0,61.0,72.0,VA Commonwealth,74.0,64.0,53.0,73.0,66.0,56,0.709677,1.0,1.0,1.0,Kansas,1.0,1.0,2.0,1.0,1.0,1,2010.0,0.941176,fae4855b-1b64-4b40-a632-9ed345e1e952

In [26]:
tourney_data.drop(columns=['start_season','Team_t','Team_o','season_o', 'kaggle_id'],inplace=True)
tourney_data.head()

,season_t,round,game_date,team_seed,team,team_id,opp_team_seed,opp_team,opp_team_id,train_rec,game_result,SAG_t,WLK_t,WOL_t,RTH_t,COL_t,POM_t,DOL_t,RPI_t,MOR_t,win_pct_t,SAG_o,WLK_o,WOL_o,RTH_o,COL_o,POM_o,DOL_o,RPI_o,MOR_o,win_pct_o
0,2013,64,2013-03-22,9,Temple,8598d1b6-106b-4083-a512-2e495729525a,8,North Carolina State,52df1e19-b142-4a76-a439-ad68455d0581,0,0,36.0,29.0,28.0,35.0,22.0,34.0,20.0,20.0,42,0.774194,45.0,41.0,52.0,41.0,42.0,43.0,48.0,49.0,31,0.647059
1,2011,64,2011-03-17,7,Temple,8598d1b6-106b-4083-a512-2e495729525a,10,Penn State,4aebd148-8119-4875-954c-66779867989b,0,1,16.0,8.0,6.0,12.0,7.0,18.0,13.0,8.0,35,0.852941,130.0,159.0,197.0,124.0,195.0,92.0,153.0,194.0,63,0.354839
2,2013,64,2013-03-21,5,Virginia Commonwealth,c1c1e6df-a383-4fbd-ba7b-32d4f9ef9518,12,Akron,56fe0ab2-e4f0-47b9-8726-9ce23ebcde20,0,0,50.0,43.0,32.0,54.0,35.0,47.0,33.0,38.0,55,0.823529,74.0,75.0,65.0,88.0,82.0,78.0,77.0,55.0,88,0.666667
3,2012,64,2012-03-15,12,Virginia Commonwealth,c1c1e6df-a383-4fbd-ba7b-32d4f9ef9518,5,Wichita State,f38b58de-3273-4723-a78b-2f918e9aa2d5,0,1,77.0,55.0,54.0,74.0,59.0,84.0,72.0,49.0,80,0.676471,64.0,61.0,64.0,61.0,57.0,63.0,73.0,60.0,62,0.750000
4,2011,8,2011-03-27,11,Virginia Commonwealth,c1c1e6df-a383-4fbd-ba7b-32d4f9ef9518,1,Kansas,fae4855b-1b64-4b40-a632-9ed345e1e952,0,0,67.0,61.0,72.0,74.0,64.0,53.0,73.0,66.0,56,0.709677,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1,0.941176